name: edu_app
description: Edu app

publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  edu_core:
    git:
      url: git@github.com:KutilinSA/edu-app-core.git
      path: edu_core
      ref: v0.0.1
  edu_localizations:
    git:
      url: git@github.com:KutilinSA/edu-app-core.git
      path: edu_localizations
      ref: v0.0.1
  edu_models:
    git:
      url: git@github.com:KutilinSA/edu-app-core.git
      path: edu_models
      ref: v0.0.1
  edu_repositories:
    git:
      url: git@github.com:KutilinSA/edu-app-core.git
      path: edu_repositories
      ref: v0.0.1
  edu_services:
    git:
      url: git@github.com:KutilinSA/edu-app-core.git
      path: edu_services
      ref: v0.0.1
  edu_ui_components:
    git:
      url: git@github.com:KutilinSA/edu-app-core.git
      path: edu_ui_components
      ref: v0.0.1

  feature_authentication:
    git:
      url: git@github.com:KutilinSA/edu-app-core.git
      path: features/feature_authentication
      ref: v0.0.1
  feature_login:
    git:
      url: git@github.com:KutilinSA/edu-app-core.git
      path: features/feature_login
      ref: v0.0.1
  feature_models_list_provider:
    git:
      url: git@github.com:KutilinSA/edu-app-core.git
      path: features/feature_models_list_provider
      ref: v0.0.1
  feature_registration:
    git:
      url: git@github.com:KutilinSA/edu-app-core.git
      path: features/feature_registration
      ref: v0.0.1
  feature_settings:
    git:
      url: git@github.com:KutilinSA/edu-app-core.git
      path: features/feature_settings
      ref: v0.0.1

  flutter:
    sdk: flutter
  flutter_bloc: 8.1.1
  formz: 0.4.1
  get_it: 7.2.0
  injectable: 2.1.0
  pull_to_refresh: 2.0.0
  sentry_flutter: 6.13.1

dev_dependencies:
  build_runner: 2.2.1
  dependency_validator: 3.2.2
  flutter_launcher_icons: 0.9.3
  flutter_native_splash: 2.2.2
  injectable_generator: 2.1.4
  lint_rules:
    git:
      url: git@github.com:KutilinSA/edu-app-core.git
      path: lint_rules
      ref: v0.0.1

flutter:
  uses-material-design: true