name: edu_app
description: Edu app

publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  edu_core:
    path: ../edu-app-core/edu_core
  edu_localizations:
    path: ../edu-app-core/edu_localizations
  edu_models:
    path: ../edu-app-core/edu_models
  edu_repositories:
    path: ../edu-app-core/edu_repositories
  edu_services:
    path: ../edu-app-core/edu_services
  edu_ui_components:
    path: ../edu-app-core/edu_ui_components

  feature_apply_project:
    path: ../edu-app-core/features/feature_apply_project
  feature_authentication:
    path: ../edu-app-core/features/feature_authentication
  feature_create_project:
    path: ../edu-app-core/features/feature_create_project
  feature_login:
    path: ../edu-app-core/features/feature_login
  feature_models_list_provider:
    path: ../edu-app-core/features/feature_models_list_provider
  feature_process_application:
    path: ../edu-app-core/features/feature_process_application
  feature_registration:
    path: ../edu-app-core/features/feature_registration
  feature_settings:
    path: ../edu-app-core/features/feature_settings

  flutter:
    sdk: flutter
  flutter_bloc: 8.1.1
  formz: 0.4.1
  get_it: 7.2.0
  injectable: 2.1.0
  pull_to_refresh: 2.0.0
  sentry_flutter: 6.13.1

dev_dependencies:
  build_runner: 2.2.1
  dependency_validator: 3.2.2
  flutter_launcher_icons: 0.9.3
  flutter_native_splash: 2.2.2
  injectable_generator: 2.1.4
  lint_rules:
    path: ../edu-app-core/lint_rules

flutter:
  uses-material-design: true