name: tools
description: Tools for automation of work processes
version: 1.0.0

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter_native_splash: 2.2.2
  git: 2.2.0
  path: 1.8.3

dev_dependencies:
  dependency_validator: 3.2.2
  lint_rules:
    git:
      url: git@github.com:KutilinSA/edu-app-core.git
      path: lint_rules
      ref: v0.0.1
